packages:
  - 'apps/*'
  - 'packages/*'
  - 'services/*'
allowBuilds:
  '@prisma/client': false
  '@prisma/engines': false
  core-js: false
  esbuild: false
  msgpackr-extract: false
  prisma: false
  puppeteer: false
  sharp: true
  unrs-resolver: true
